/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
import com.mongodb.BasicDBObject;
import com.mongodb.*;
import javax.swing.JOptionPane;

public class Admin_rights extends javax.swing.JFrame {

    /**
     * Creates new form Admin_rights
     */
    public Admin_rights() {
        initComponents();
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newAdd_button = new javax.swing.JButton();
        change_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logout_button = new javax.swing.JButton();
        emp_list_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newAdd_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newAdd_button.setText("New Employee");
        newAdd_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAdd_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(newAdd_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 190, 32));

        change_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        change_button.setText("Change Employee");
        change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(change_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 180, 32));

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 6, 6));
        jLabel1.setText("WELCOME ADMIN !!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 260, 28));

        logout_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logout_button.setText("LogOut");
        logout_button.setBorder(null);
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(logout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 100, 31));

        emp_list_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emp_list_button.setText("Employee Details");
        emp_list_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_list_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(emp_list_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 190, 33));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Session Income");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 200, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\DBMS Project\\Parking_Project\\Images\\oak-wood.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 610, 470));
        jLabel2.getAccessibleContext().setAccessibleName("PARKING ENTRY MANAGEMENT");
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Parking Management System");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newAdd_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAdd_buttonActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        new admin_Add_newEmp().setVisible(true);
        
    }//GEN-LAST:event_newAdd_buttonActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        new login_page().setVisible(true);
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_buttonActionPerformed
        // TODO add your handling code here:
           setVisible(false);
           new admin_change_Emp().setVisible(true);
    }//GEN-LAST:event_change_buttonActionPerformed

    private void emp_list_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_list_buttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new emp_detail_table().setVisible(true);
    }//GEN-LAST:event_emp_list_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Session_details().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_rights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_rights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_rights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_rights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_rights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change_button;
    private javax.swing.JButton emp_list_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logout_button;
    private javax.swing.JButton newAdd_button;
    // End of variables declaration//GEN-END:variables
}
